name=Small-Libs
version=1.0.0
author=Serhii Lebedenko
maintainer=Serhii Lebedenko (slebedenko@gmail.com)
sentence=A set of small functions for implementing typical algorithms in Arduino.
#paragraph=
category=Communication
url=https://github.com/SerhiiLe/Small-Libs
architectures=esp8266,esp32